### ISSUE TITLE
Not able to find Share button at the top

### ISSUE THREAD

**Issue by alpha-nome** [QuantStack/jupyterlab#6]
Hey,

Firstly thanks for this. I've been waiting for this for quite sometime. I did setup everything and tried this.

I was able to test it in multiple browsers by just copying the URL. But I was not able to get the share button on top like the demo. Can you guide me on where I'm making an error. Thanks

**Comment by jtpio** [comment]
Thanks @alpha-nome.

Did you set this up locally from source?

If so you might need to manually install the `jupyterlab-link-share` extension: https://github.com/jupyterlab-contrib/jupyterlab-link-share

It's already part of this repo, but only for the dev Binder setup:

https://github.com/QuantStack/jupyterlab/blob/e5ce2971f972412d6f5e2ebaf287e03ad487477f/binder/environment.yml#L5

**Comment by alpha-nome** [comment]
Yeah I did. 

Okay. Got it. Working now on local docker. 

I'm getting a strange error when I'm deploying this jupyterhub


Traceback (most recent call last):
  File "/opt/conda/envs/yjupyter/bin/jupyter-lab", line 33, in <module>
    sys.exit(load_entry_point('jupyterlab', 'console_scripts', 'jupyter-lab')())
  File "/opt/conda/envs/yjupyter/bin/jupyter-lab", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/opt/conda/envs/yjupyter/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/opt/conda/envs/yjupyter/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: jupyterlab


I've been trying to debug this. Not able to figure out whats happening. I tried giving absolute path for jupyterlab also. But no luck

Should this jupyterlab path be the one that we build?

**Comment by jtpio** [comment]
Looks like JupyterLab is not installed?

To test the `yjupyter` branch it's better to run JupyterLab in dev mode for now. Not sure it would work otherwise.

You might want to check the contributing guide to see which commands to run to setup the dev environment: https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#setting-up-a-local-development-environment

**Comment by alpha-nome** [comment]
Hey! Just figured out the error. 

I installed jupyterlab in the /home/jovyan folder which was getting overridden when I start a new container on jupyter hub. Moved it to another internal folder and it worked.

Thanks so much.

**Comment by jtpio** [comment]
Great!

Closing as answered, thanks a lot for testing!

Don't hesitate to open a new issue if you have more questions, or post your feedback on the PR in the JupyterLab repo: https://github.com/jupyterlab/jupyterlab/pull/9785
